# Source - https://stackoverflow.com/a
# Posted by Makrushin Evgenii, modified by community. See post 'Timeline' for change history
# Retrieved 2025-11-20, License - CC BY-SA 4.0

FROM apache/airflow:2.6.0-python3.9
WORKDIR /opt/idp-bigdata/airflow
COPY requirements.txt .
RUN pip install -r requirements.txt

