version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - type: volume
        source: postgres-db-volume
        target: /var/lib/postgresql/data
        volume: {}
    networks:
      - airflow-net
    build: .

  airflow-webserver:
    image: apache/airflow:2.6.0-python3.9
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__FERNET_KEY=NPoJUcgUcHhCAVKbskBQG0g2oZlJuN_zmn21Nt-F10w=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    networks:
      - airflow-net
    depends_on:
      - postgres
    command: bash -c "airflow db init && airflow webserver"
    build: .

  airflow-scheduler:
    image: apache/airflow:2.6.0-python3.9
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__FERNET_KEY=NPoJUcgUcHhCAVKbskBQG0g2oZlJuN_zmn21Nt-F10w=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - airflow-net
    depends_on:
      - postgres
    command: bash -c "airflow scheduler"
    build: .

  airflow-init:
    image: apache/airflow:2.6.0-python3.9
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    networks:
      - airflow-net
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    build: .

networks:
  airflow-net:
    external: true

volumes:
  postgres-db-volume:
